name: atmos-tower 
channels:
  - conda-forge
  - defaults
  - pyviz
dependencies:
  - python=3.9
  - arm_pyart
  - act-atmos
  - matplotlib
  - pyserial
  - hvplot
  - jupyterlab
  - holoviews
  - geoviews
  - cartopy
  - numpy
  - dask
  - dask-labextension
  - distributed
  - xarray
  - pandas
  - datashader
  - geopandas
  - fiona
  - pip
  - pip:
    - -r doc-requirements.txt
